### ISSUE TITLE
General feedback

### ISSUE THREAD

**Issue by rglassett** [zackattack01/breedly#6]
I like the proposal, but it suffers from being a bit vague and disorganized. Please move everything to Markdown so you (and we) can get a better sense of your progress. As I said in the other issue, everything will be Backbone, so that doesn't get its own phase; the order of everything else looks okay, but you could probably separate it a bit more (and maybe add some bonus phases).

**Comment by zackattack01** [comment]
Hey Ryan when you get a chance if you could let me know how this looks that would be great.
I moved the user location to top of bonus, this one I really need to get to but don't have a specific plan for calculating distance and it isn't absolutely necessary for the mvp.  I tried to hit everything mentioned and clarify a few things.  Also I totally get keeping up with backbone the whole time but just so we're clear the 3 days of css styling on day two was a poorly implemented joke that was supposed to fall off the page if you clicked the link, my b. thanks again

**Comment by rglassett** [comment]
This looks a lot better, Zack. Thanks for making the changes!
